# Generated by Django 3.1.4 on 2021-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
