# Generated by Django 3.1.4 on 2021-04-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_auto_20210421_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
