# Generated by Django 3.1.4 on 2021-04-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0006_auto_20210422_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
